export const genres = [
  {"genreName":"hip-hop",
    "songs":[
      {"id":"HdOhwPovkHI","title":"Check yo self - ice cube"},
      {"id":"CXdTShfFPYM","title":"Tierra Whack - only child"},
      {"id":"Wzurw1w3AjY","title":"Gold teeth - blood orange"},
      {"id":"FUXX55WqYZs","title":"Who dat boy - tyler, the creator"},
      {"id":"iOtRxcTMsHc","title":"Poetic justice - kendrick lamar"},
      {"id":"XXMHQ410P-c","title":"Solo (reprise) - frank ocean"},
      {"id":"t5gh4uX-X40","title":"Bank - earthgang"},
      {"id":"0yCJs3GrjpE","title":"It ain’t hard to tell - nas"},
      {"id":"F-4KiszXxHM","title":"Jazz - mick jenkins"},
      {"id":"4cucHc2vef4","title":"Boogie - brockhampton"},
      {"id":"aIXyKmElvv8","title":"Ready or not - fugees"},
      {"id":"F2r-8fd1jVE","title":"Wax on - injury reserve"},
      {"id":"AC4bb9Q9-04","title":"King kunta - kendrick lamar"},
      {"id":"tYVebHOrlZU","title":"Self - noname"},
      {"id":"f--ZuvER98U","title":"Casket pretty - noname"},
      {"id":"8KxXsQjJsIw","title":"Bissonnet - maxo kream"},
      {"id":"zI19cWqsLhA","title":"Pimp tha pen - dj screw"},
      {"id":"lDWeob50YY8","title":"Realer - Megan Thee Stallion"},
      {"id":"sTTU-T9-RTs","title":"Rnp - ybn cordae"},
      {"id":"OJyy_stKS9c","title":"Mood - rico nasty"},
      {"id":"1og6jfhUPxE","title":"Cheat code - rico nasty"}
    ]
  },
  {"genreName":"rb",
    "songs":[
      {"id":"lnUV4cz0gv8","title":"Cranes in the Sky - Solange"},
      {"id":"OxdCR6wwoXs","title":"Diddy Bop - Noname"},
      {"id":"lovts-q5s0s","title":"Come Over - the internet"},
      {"id":"vT02Lo5WhLI","title":"Whipped cream - ari lennox"},
      {"id":"YzI76YfVXD4","title":"4 leaf clover - ravyn lenae"},
      {"id":"kobOjAkSrhk","title":"Nothing burns like the cold - snoh allegra"},
      {"id":"pvU4b4N1-QU","title":"Dear april - frank ocean"},
      {"id":"TftBcX-kCQc","title":"Do u wrong - leven kali"},
      {"id":"9G-vhg8T2rc","title":"Hair down - sir"},
      {"id":"DBkjjuAoajY","title":"Petrol bliss - choker"},
      {"id":"7HiB-hNt_mw","title":"Florence - loyle carner"},
      {"id":"6Fc4QwsTz_g","title":"Shades of blue - kelsey lu"},
      {"id":"i9PmsucjHrM","title":"Color theory - kari faux"},
      {"id":"NclTIViKiyE","title":"George-arlo parks"},
      {"id":"6UpjbnDfbRU","title":"Good for you - blood orange"},
      {"id":"3xotpsdLS6c","title":"Headaches - raveena"},
      {"id":"dta4heZacZE","title":"Polly - moses sumney"},
      {"id":"opRwZJsOe0w","title":"Montego bae - noname"},
      {"id":"uzS3WG6__G4","title":"Pink and white frank ocean"},
      {"id":"HK90QhbzIkw","title":"Wikipedia - jean deaux"},
      {"id":"jEvv2PR0ZeI","title":"Sticky - raven lenae"},
      {"id":"cXITfPnI__o","title":"Grey luh - berhana"},
      {"id":"BS0rGNEdGzs","title":"Self importance - kilo kish"}
    ]
  },
  {"genreName":"funk",
    "songs":[
      {"id":"ftdZ363R9kQ","title":"Superstition - Stevie Wonder"},
      {"id":"S6Y1gohk5-A","title":"Purple Rain - Prince"},
      {"id":"l7vRSu_wsNc","title":"Raspberry Beret - Prince"},
      {"id":"MhC_iLBrSUY","title":"What’s Going On - Marvin Gaye"},
      {"id":"HhPu6GEoad8","title":"Brick House - Commodores"},
      {"id":"ALzISTfdXpQ","title":"I Got to Groove - Tower of Power"},
      {"id":"vuDCi5neNMM","title":"Tell Me Something Good - Rufus and Chaka Khan"},
      {"id":"NOa5UOHdwnc","title":"Thank You (Falettinme Be Mice Elf Agin) - Sly & the Family Stone"},
      {"id":"T1NW57lk5fY","title":"Maggot Brain - Funkadelic"},
      {"id":"50W9W0RHvwI","title":"Move on Up - The Dynamics"},
      {"id":"yURRmWtbTbo","title":"Don’t Stop ‘Til You Get Enough - Michael Jackson"},
      {"id":"6To0fvX_wFA","title":"Signed, Sealed, Delivered (I'm Yours) - Stevie Wonder"},
      {"id":"EnNgASBdCeo","title":"Sir Duke - Stevie Wonder"},
      {"id":"oTUSeac7IuQ","title":"When Doves Cry - Prince"},
      {"id":"C02SFbc4zmM","title":"Daddy Rich - Rose Royce"},
      {"id":"42YGprrAOj0","title":"Sing a Simple Song - Sly & the Family Stone"},
      {"id":"qchPLaiKocI","title":"Get Down On It - Kool & the Gang"},
      {"id":"JTvlujbJ5vg","title":"Play that Funky Music - Wild Cherry"},
      {"id":"5SrQ9graFWQ","title":"Get Up (I Feel Like Being A) Sex Machine - James Brown"},
      {"id":"71l85z2bXAs","title":"Papa Was a Rolling Stone - the Temptations"},
      {"id":"eAk3ayxi8Gk","title":"Water No Get Enemy - Fela Kuti"}
    ]
  },
  {"genreName":"bedroom-pop",
    "songs":[
      {"id":"Mf5XrSuQ4R8","title":"Grandfather Clock - Thea"},
      {"id":"2p7m2iY-WSY","title":"Hit Me Up - Omar Apollo"},
      {"id":"A0gpfwZP_To","title":"Ugotme - Omar Apollo"},
      {"id":"WMp0ZyQWKf4","title":"Foolsong - Still Woozy"},
      {"id":"GYEKlxUty84","title":"B Cool - MaGroove"},
      {"id":"dvWZt6SuNtI","title":"Eternally 12 - Melanie Faye"},
      {"id":"zC3GHcPN4EQ","title":"Paradise - Rex Orange County"},
      {"id":"sTQNJT7OZew","title":"If You Want To - beabadoobee"},
      {"id":"L9HYJbe9Y18","title":"Bags - Clairo"},
      {"id":"L9l8zCOwEII","title":"Sofia - Clairo"},
      {"id":"SRbzuwYMyDE","title":"Flaming Hot Cheetos - Clairo"},
      {"id":"QkeehQ8D_VM","title":"Hello? - Clairo"},
      {"id":"oFYOxVeQBTo","title":"Drowsy - Banes World"},
      {"id":"GM8YDU6ZjBw","title":"Gap in the Clouds - Yellow Days"},
      {"id":"7VVLDCR4wPM","title":"Know Love - Rex Orange County"},
      {"id":"xqC--4paOTM","title":"Can’t be // How u feel - Billy Lemos"},
      {"id":"5ohMAVDUswQ","title":"Dreamz - Sara King"},
      {"id":"qTe6toWNC6s","title":"Smoke Song Interlude - Sebastian Roca"},
      {"id":"OeCS-DZsgKM","title":"Moon Undah Water - Puma Blue"},
      {"id":"jCkBxmPbohk","title":"Midnight Blue - Puma Blue"},
      {"id":"WMp0ZyQWKf4","title":"Foolsong - Still Woozy"},
      {"id":"F_8XzWXleoY","title":"Lucy - Still Woozy"},
      {"id":"V0X-SWiDr1g","title":"Sunflower - Rex Orange County"}
    ]
  },
  {"genreName":"neo-soul",
    "songs":[
      {"id":"6giKIu5jUvA","title":"Almeda - Solange"},
      {"id":"T6QKqFPRZSA","title":"Doo wop - lauryn hill"},
      {"id":"_W14wK4QGh4","title":"Stay flo - solange"},
      {"id":"D7rm9t5S4uE","title":"Ascension - maxwell"},
      {"id":"0a4PD4SwEAs","title":"Song 32 - noname"},
      {"id":"0ZARYxRmNWg","title":"Love is stronger than pride - solange"},
      {"id":"OQuQV6u8-tk","title":"Jailer - Asa"},
      {"id":"2j4qvVyRgRk","title":"Out my mind, just in time - erykah badu"},
      {"id":"Gb76TgCUqAY","title":"Are We Still Friends - tyler the creator"},
      {"id":"t-E2gm0a_N0","title":"Earfquake - tyler the creator"},
      {"id":"mXiFHDfvn4A","title":"Moon river - frank ocean"},
      {"id":"wVzvXW9bo5U","title":"Can’t take my eyes off you - lauryn hill"},
      {"id":"hToe5L41y6c","title":"Get up - amel larrieux"},
      {"id":"uhjtjOUsQ6c","title":"Culture - kaytranada"},
      {"id":"2w6udgiojlE","title":"Sweet Love - Anita baker"},
      {"id":"ajOCGskHs2A","title":"What you need - kaytranada"},
      {"id":"ygkIMT4vsTE","title":"Whathegirlmuthafuckinwannadoo - the coup"},
      {"id":"n0tWINt8Ofk","title":"I want war (but i need peace) - kali uchis"},
      {"id":"T3CunfPYkME","title":"The charade - d’angelo"},
      {"id":"SxVNOnPyvIU","title":"How does it feel - d’angelo"},
      {"id":"ISCFeQ7963A","title":"Back to the future (part i) - d’angelo"},
      {"id":"xRzbLQ_WKPs","title":"Dark red - steve lacy"},
      {"id":"KTh8ermjdbI","title":"Some - steve lacy"}
    ]
  },
  {"genreName":"post-punk",
    "songs":[
      {"id":"6qHClRnSQYM","title":"Punks - Matt Champion"},
      {"id":"l03ybrIMxKo","title":"Fangs - matt champion"},
      {"id":"JRiSdAe8sGY","title":"Call this # now - the garden"},
      {"id":"rW43Sq4Rgjo","title":"Stylish spit - the garden"},
      {"id":"c7rsPaDXtng","title":"All access - the garden"},
      {"id":"N5an4_Iw7ZU","title":"Clench to stay awake - the garden"},
      {"id":"tkOr12AQpnU","title":"Bizarre love triangle - new order"},
      {"id":"VaMU_6sI3j8","title":"Neat neat neat - the damned"},
      {"id":"iAmZPxuMHsc","title":"Emergency blimp - king krule"},
      {"id":"kfFhOsjz7jc","title":"Vidual - king krule"},
      {"id":"2XzXLzA2Hrc","title":"Half man half shark - king krule"},
      {"id":"k-lg3v4HtBA","title":"Comet face - king krule"},
      {"id":"OMMlPs0O2rw","title":"Blue train lines - mount kimbie"},
      {"id":"Ncq7I-EHQ0Q","title":"Midnight 01 (deep sea diver) - king krule"},
      {"id":"PCZ2Dp6Is9M","title":"Heads will roll - yeah yeah yeahs"},
      {"id":"j1-xRk6llh4","title":"Wolf like me - tv on the radio"},
      {"id":"XV765LFwHJE","title":"Tenement roofs - glorious din"},
      {"id":"uIYo1okOm9U","title":"Big joanie - dream no 9"},
      {"id":"UzPh89tD5pA","title":"Rip it up - orange juice"},
      {"id":"ImIESKQKKJo","title":"Blister in the sun - violent femmes"},
      {"id":"5BIElTtN6Fs","title":"Disorder - joy division"}
    ]
  }
];